// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Staffing.Infrastructure.Persistence;

#nullable disable

namespace Staffing.Infrastructure.Migrations
{
    [DbContext(typeof(StaffingDbContext))]
    [Migration("20251225200523_FixStaffingMetricTable")]
    partial class FixStaffingMetricTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Staffing.Domain.Entities.Division", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsTotalLevel")
                        .HasColumnType("boolean");

                    b.Property<string>("NameOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("NameOriginal");

                    b.HasIndex("ParentId");

                    b.ToTable("division", (string)null);
                });

            modelBuilder.Entity("Staffing.Domain.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReportTemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReportTemplateKey")
                        .IsUnique();

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("Staffing.Domain.Entities.ReportImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DqErrorsCount")
                        .HasColumnType("integer");

                    b.Property<int>("DqWarningsCount")
                        .HasColumnType("integer");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("PositionId", "ReportDate", "SourceFileHash", "TemplateVersion")
                        .IsUnique();

                    b.ToTable("report_import", (string)null);
                });

            modelBuilder.Entity("Staffing.Domain.Entities.StaffingMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("MetricDate")
                        .HasColumnType("date");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MetricUnit")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetricValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<int>("ValueSource")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("MetricDate");

                    b.HasIndex("MetricKey");

                    b.HasIndex("PositionId");

                    b.HasIndex("ImportId", "DivisionId", "PositionId", "MetricKey", "MetricDate")
                        .IsUnique();

                    b.ToTable("staffing_metric", (string)null);
                });

            modelBuilder.Entity("Staffing.Domain.Entities.Division", b =>
                {
                    b.HasOne("Staffing.Domain.Entities.Division", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Staffing.Domain.Entities.ReportImport", b =>
                {
                    b.HasOne("Staffing.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Staffing.Domain.Entities.StaffingMetric", b =>
                {
                    b.HasOne("Staffing.Domain.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Staffing.Domain.Entities.ReportImport", "Import")
                        .WithMany("Metrics")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staffing.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Import");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Staffing.Domain.Entities.Division", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Staffing.Domain.Entities.ReportImport", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
